import os

BASE_URL = os.getenv("INTEGRATION_BASE_URL", "http://localhost:8000")
REQUEST_TIMEOUT_SECONDS = float(os.getenv("INTEGRATION_REQUEST_TIMEOUT_SECONDS", "10"))
EVENTUAL_TIMEOUT_SECONDS = float(os.getenv("INTEGRATION_EVENTUAL_TIMEOUT_SECONDS", "45"))
POLL_INTERVAL_SECONDS = float(os.getenv("INTEGRATION_POLL_INTERVAL_SECONDS", "1"))
